CREATE TABLE IF NOT EXISTS public.genres (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title VARCHAR NOT NULL,
	CONSTRAINT genres_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mpa_ratings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title VARCHAR NOT NULL,
	CONSTRAINT mpa_ratings_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	email VARCHAR NOT NULL,
	login VARCHAR NOT NULL,
	name VARCHAR,
	birthday DATE,
	CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.films (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR NOT NULL,
	description VARCHAR(200),
	release_date DATE,
	duration BIGINT,
	mpa_rating_id INTEGER,
	CONSTRAINT films_pk PRIMARY KEY (id),
	CONSTRAINT fk_mpa_rating_id
    	FOREIGN KEY (mpa_rating_id)
    	REFERENCES public.mpa_ratings (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.film_likes (
	film_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	CONSTRAINT fk_film_id
    	FOREIGN KEY (film_id)
    	REFERENCES public.films (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT,
    CONSTRAINT fk_user_id
    	FOREIGN KEY (user_id)
    	REFERENCES public.users (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.film_genres (
	film_id BIGINT NOT NULL,
	genre_id BIGINT NOT NULL,
	CONSTRAINT fk_film_id
    	FOREIGN KEY (film_id)
    	REFERENCES public.films (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT,
    CONSTRAINT fk_genre_id
    	FOREIGN KEY (genre_id)
    	REFERENCES public.genres (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.user_friends (
	user_id BIGINT NOT NULL,
	friend_id BIGINT NOT NULL,
	status BOOLEAN default false NOT NULL,
	CONSTRAINT fk_user_id
    	FOREIGN KEY (user_id)
    	REFERENCES public.users (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT,
    CONSTRAINT fk_friend_id
    	FOREIGN KEY (friend_id)
    	REFERENCES public.users (id)
    	ON UPDATE RESTRICT
    	ON DELETE RESTRICT
);

INSERT INTO public.genres (id, title) VALUES
    (1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Мультфильм'),
    (4, 'Триллер'),
    (5, 'Документальный'),
    (6, 'Боевик');

INSERT INTO public.mpa_ratings (id, title) VALUES
    (1, 'G'),
    (2, 'PG'),
    (3, 'PG-13'),
    (4, 'R'),
    (5, 'NC-17');
